### ISSUE TITLE
Header/footer placeholders aren't specific to the viewer that looks at them

### ISSUE THREAD

**Issue by Karltroid** [WiIIiam278/Velocitab#38] opened 2023-04-06 00:43 UTC
On my server, I have the player's money on the bottom of the tab list with the %vault_eco_balance_formatted% placeholder. There is an issue where it will show your money initially, but then it will seemingly rotate through each player's money in the tab list every time it updates. So say I have $10,000 and Joe has $100. I will log in, and see $10,000, 5 seconds later I will see "I" have $100, so it's showing me Joe's vault balance.

**Comment by WiIIiam278** [comment] 2023-04-17 15:44
This is a PAPIProxyBridge bug caused by caching not being user-specific, fixed in PAPIProxyBridge v1.2 (soon!)

**Closed by WiIIiam278** 2023-04-17 15:44 UTC
Labels: type: bug
