### ISSUE TITLE
Config Issue with Tildes and Unicode 😅

### ISSUE THREAD

**Issue by Martinez662004** [WiIIiam278/Velocitab#156] opened 2024-02-05 22:50 UTC
Hey @WiIIiam278 ,

Hope you're doing awesome! 🚀 Quick heads up - ran into a quirk with your Minecraft plugin's config. Seems like it's not vibing well with tildes (á, é, í, ó, ú,) and Unicode stuff.

Using those cool characters messes up the config, causing a bit of chaos. 😬 Thought I'd give you the heads up, and maybe it's an easy fix on your end?

If you need more deets or if I can help in any way, just shout. Thanks a bunch! 🙌

Cheers.

**Comment by alexdev03** [comment] 2024-02-05 22:52
Hi, could you try using the latest alpha build on modrinth? https://modrinth.com/plugin/velocitab/versions

**Comment by WiIIiam278** [comment] 2024-02-08 15:12
Should already have been fixed in https://github.com/WiIIiam278/Velocitab/commit/63ed22527b75ba505ad94bb538307d46f8d209d6 &mdash; was caused by ConfigLib doing stuff in ASCII instead of UTF-8

**Closed by WiIIiam278** 2024-02-08 15:12 UTC
